

name: Testing The Client-Server

on: push

permissions:
  contents: read

jobs:
  unit_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Run tests
        run: |
          pytest e2e_test.py
          cat server.log && cat client.log
